config/routes.rb
Rails.application.routes.draw do
  devise_for :renters
  devise_for :agents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'main#index'
get '/delimage/:id'=>"agent#delimage", as: :delimage
get '/unrent/:id' => 'properties#unrent' , as: :unrent
get '/remove/:id' => 'properties#remove' , as: :remove
get '/addprop/:id' => 'properties#new', as: :addprop
get '/viewproperty/:id' => 'properties#show', as: :viewproperty
get '/displayprop', action: :show, controller: 'agent'
get '/viewprop', action: :show, controller: 'renter'
get '/addapproach/:id', action: :addapproach, controller: 'agent', as: :addapproach
get '/addrentedprop/:id', action: :addrented, controller: 'properties', as: :addrentedprop
get '/addwishlist/:id', action: :addwish, controller: 'properties', as: :addwishlist
get '/rentedlistpath', action: :showrented, controller: 'properties', as: :rentedlistp
get '/wishlistpath', action: :showwish, controller: 'properties', as: :wishlistp
post '/reviews', action: :create, controller: 'review', as: :reviews
get '/delimageattachment/:id', action: :delete_image_attachment, controller: :agent, method: :delete,as: :delimageattachment 
get '/viewapproachedlist/:id', action: :viewapproach, controller: 'agent',as: :viewapproach
post '/create', action: :create, controller: :company
resources :properties
resources :company
end

app/models/agent.rb
class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable 
         
    has_many :properties,dependent: :destroy
    


validates :password, 
            format: { with: /\A(?=.*\d)(?=.*[A-Z])(?=.*\W)[^ ]{7,}\z/,
                      message: 'Password should have more than 7 characters including 1 uppercase letter, 1 number, 1 special character'
                    }

end

app/controllers/agent_controller.rb
class AgentController < ApplicationController
    def login
        @agentl=Agent.new
    end
    <<-manualvalidation
    def loginvalidation
        @agentl=Agent.new(params.require(:@agentl).permit(:email, :password))
       check_email=@agentl.email
       @temporaty=(Agent.where(email:check_email)).take
        if @temporaty!= nil
            tempstring=@agentl.password
            originalpass=@temporaty.password
        if tempstring.eql?(originalpass)  
            redirect_to @temporaty
        else
            render 'login'
        end
        else
            render 'login'
        end
    end
    manualvalidation

    def new
        @agent=Agent.new()
        @company=Company.new()
       
        
    end
    def create
        @agent=Agent.new(agent_params)
        @agent.role="Admin"
        @agent.save
    end
    def show
    @agent = current_agent 
  	@properties = @agent.properties 
    end
    def viewapproach
        @approach=Approach.new()
        @property=Property.find(params[:id])
        @approachlist=Approach.where(property_id:@property.id).all
        if @property.flag == 1  
        @rentedp=Rentedlist.where(property_id: @property.id).take
        end
    end
    def addapproach
        @approach=Approach.new()
        @property=Property.find(params[:id])
        @renter=current_renter
        @approach.property_id=@property.id
        @approach.renter_id=@renter.id
        @approach.approachflag = 1
        if @approach.save
        redirect_to viewproperty_path(@property)
        else
        redirect_to viewproperty_path(@property), notice: "Unable to add approaches soryy!!try after some months"
        end
    end
   
    def delimage
        @property=Property.find(params[:id])
                
    end
    def delete_image_attachment
        
            @image = ActiveStorage::Attachment.find(params[:id])
            @image.purge
            redirect_back(fallback_location: request.referer) 
    end
    private 
  def agent_params 
    params.require(:@agent).permit(:email, :password, :contact, :address, :name)
  end 
    
end

app/helpers/agent_helper.rb
module AgentHelper
end

app/views/agent/delimage.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.br{
  margin-left:4%;
}
body{
	margin:0;
	color:#6a6f8c;
	background:#808080;
	font:600 16px/18px 'Open Sans',sans-serif;
  background-color: ; 
}
.wt{
  color:white;
}
</style>
</head>
<body>


<div class="row">
<div style="text-align:center; color:white;"> Edit/Delete your property images</div>
<br><br>

 <%(0...@property.images.count).each do |img| %>
<%= image_tag(@property.thumbnail(img),class:"br")%>
 <%= link_to 'Remove', delimageattachment_url(@property.images[img]),class:"wt" %>
 <%end%>

</div>

</body>
</html>

app/views/agent/show.html.erb
<% #Displaying all the properties added by the agent in agent account%>

<!DOCTYPE html>
<html>
<head>
	
<style >

</style>

<ul>
  <li><%= link_to "Addproperties", addprop_path(@agent) ,class:"active"%></li>
   <li style="float:right"><%= link_to "logout", destroy_agent_session_path, method: :delete %></li>
</ul>


<br>
<div class="center">Welcome <%=@agent.name%></div>
<h2 class="center"> Your Properties</h1>

	<div class="login-form"> <div class="sign-in-htm">
	
	<% @agent.properties.each do |prop|%>
		<div class="clearfix">
		<div class="box">
		<button class="btn1"> <%=link_to "Edit" ,edit_property_path(prop)%> </button>
 		<button class="btn"><%=link_to "Applications", viewapproach_path(prop)%></button>

		<button class="btnr" ><%= link_to 'Delete', property_path(prop),
        	            method: :delete, data: { confirm: 'Are you sure?' } %> </button> 

		<h2 class="propname"><%= prop.name%><br></h2>
		

	<%(0...prop.images.count+1 - prop.images.count).each do |img| %>
   <a href=""> <%= image_tag(prop.thumbnail(img),class:"br") %></a>
   <%end%>
   <br><br>
   		<span class="textd">Property Location :</span>
		<span class="border"><%= prop.address %></span><br>
		<div><span class="textd" >Rent($)</span> &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&ensp;<span class="textd">Bedrooms</span></div>
		<div class="rent"><%= prop.rent%></div>

		<div class="bedrooms"><%= prop.bedrooms%></div><br><br>
		<span class="textd">City</span>
		<div class="border"><%=prop.city%></div>
		
		<span class="textd" >About Property</span>

		<span class="border"><%= prop.description%></span>
			</div>
		<div>
		<% end %>

app/views/agent/viewapproach.html.erb
<style>


table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 8px;
  text-align: left;
  border-bottom: 1px solid #ddd;
}

tr:hover {background-color: #b3b3b3;}

</style>

<ul>
  <li><%= link_to "back", displayprop_path(@property) ,class:"active"%></li>
   <li style="float:right"><%= link_to "logout", destroy_agent_session_path, method: :delete %></li>
</ul>
<h1 text-align=center>Renters who are approached for this property</h1>

<table width="50%" cellspacing="0">
<thead>
<th width="100">Renter Name</th>
<th width="150">Email</th>
<th width="90">Contact</th>
<th width="50">Status</th>
</thead>
<tbody>
<%@approachlist.each do |approach|%>
<% @rentername=Renter.find(approach.renter_id)%>
<%#for dipsplay buttons%>
<tr>
<td><%= @rentername.name%></td>
<td><%=@rentername.email%></td>
<td><%=@rentername.contact%></td>
<% if @property.flag == 1%>
<% if @rentedp.renter_id == @rentername.id%>
<td><%="Already Accepted"%></td>
<%else%>
<td><%="NIL"%></td>
<%end%>
<%else%>
<td><%=link_to "Accept",addrentedprop_path(approach)%></td>
<%end%>
</tr>
<%end%>

</tbody>
</table>