config/routes.rb
Rails.application.routes.draw do
  devise_for :renters
  devise_for :agents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'main#index'
get '/delimage/:id'=>"agent#delimage", as: :delimage
get '/unrent/:id' => 'properties#unrent' , as: :unrent
get '/remove/:id' => 'properties#remove' , as: :remove
get '/addprop/:id' => 'properties#new', as: :addprop
get '/viewproperty/:id' => 'properties#show', as: :viewproperty
get '/displayprop', action: :show, controller: 'agent'
get '/viewprop', action: :show, controller: 'renter'
get '/addapproach/:id', action: :addapproach, controller: 'agent', as: :addapproach
get '/addrentedprop/:id', action: :addrented, controller: 'properties', as: :addrentedprop
get '/addwishlist/:id', action: :addwish, controller: 'properties', as: :addwishlist
get '/rentedlistpath', action: :showrented, controller: 'properties', as: :rentedlistp
get '/wishlistpath', action: :showwish, controller: 'properties', as: :wishlistp
post '/reviews', action: :create, controller: 'review', as: :reviews
get '/delimageattachment/:id', action: :delete_image_attachment, controller: :agent, method: :delete,as: :delimageattachment 
get '/viewapproachedlist/:id', action: :viewapproach, controller: 'agent',as: :viewapproach
post '/create', action: :create, controller: :company
resources :properties
resources :company
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :approaches, dependent: :destroy
    has_many_attached :images
    validate :image_type
def thumbnail input
    return self.images[input].variant(resize: '300X250>').processed
end

    private 
    def image_type
        if images.attached? == false
            errors.add(:images, "missing")
        end
        images.each do |image|
            if !image.content_type.in?(%('image/jpeg image/png'))
                errors.add(:images , "should be jpeg or png")
            end
        end
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    #for creating a new agent
    def new
       @agent =current_agent
       @properties=Property.new
    end

    #display property 
    def show
      @property=Property.find(params[:id])
      @renter =current_renter
      @review=Review.new()
      @review.property_id=@property.id
      # to check whether the property is rented or not in the view side
      @check= Rentedlist.where(property_id: @property.id).take
      @reviewslist=Review.where(property_id: @property.id).all
      #for approachlist to check if it is already approached by the current renter or not
      @approachflag=0
      @appr=Approach.where(renter_id:@renter.id).all
      #loop through the renters to find whether the propertyis already approached or not
      @appr.each do |prp|
          if prp.property_id == @property.id
          @approachflag=1
          puts "#{@approachflag}"
          break
        end
        #ending the loop
      end
    end


    # Add a particular property in rented list and sending email to Agent
    def addrented
      @adder=Rentedlist.new()
      @approach=Approach.find(params[:id])
      @adder.renter_id=@approach.renter_id
      @adder.property_id=@approach.property_id
      @property=Property.find(@approach.property_id)
      @currentflag=0;
      if @adder.save
        # getting agent, property, renters object for sending email
        @agent=current_agent
        @renter= Renter.find(@approach.renter_id)
        #flag updation for rented or not
        @property.update(flag: 1)
        #sending email to renters that Agent has accepted his approach
        UserMailer.propertyrented(@renter,@agent,@property).deliver


       # sending email to those who are approached as it was allocated for someone except the allocated renter
       @approach.destroy
         @check=Approach.where(property_id: @property.id).all
         @check.each do |obj|
         @renter=Renter.find(obj.renter_id)
         @agent=Agent.find(@property.agent_id)
          UserMailer.propertybooked(@renter,@agent,@property).deliver_now
         end


        redirect_to viewapproach_path(@property), notice: "An email has been sent to the respective Renter regarding your acceptance , he will ge back you in short"
      else
      redirect_to viewapproach_path(@property), notice: "Sorry you have already accepted this renter"
      end
    end

    #Adding a particular property to wishlist
    def addwish
      @adder=Wishlist.new()
      @propertylist=Property.find(params[:id])
      @renter=current_renter
      @adder.renter_id=@renter.id
      @adder.property_id=@propertylist.id
      if @adder.valid?
        if @adder.save
        redirect_to viewprop_path(@propertylist), notice: "Added to Ur Wishlist"
        end
      else
        redirect_to viewprop_path(@propertylist), notice: "You had already added it to wishlist"

      end
    end

    #Adding a new property
  def create
        @properties=Property.new(property_params)
        @properties.flag=0
        @agent=current_agent
        @properties.agent_id = @agent.id
        if @properties.valid?
             @properties.save
            redirect_to displayprop_path
        else
            flash.now[:messages] = @properties.errors.full_messages
              render :new
        end
    end


    #Modifiying the existing property
    def edit
        @property=Property.find(params[:id])
    end



    #updating the particular modification to that property
    def update
        @property=Property.find(params[:id]) 
        if @property.update(params[:property].permit(:name,  :agent_id,:address, :city, :rent, :bedrooms,:description,images: []))
          redirect_to displayprop_path
        else
          render 'edit'
        end
    end



    #Removing a property from the propertytable
    def destroy
        @property = Property.find(params[:id])
        @property.destroy!
        redirect_to displayprop_path
     end



    #Display the property from Rentedlist table
      def showrented
        @renter=current_renter
        @properties=Rentedlist.where(renter_id: @renter.id)
        #@properties=Property.where(id: @properties.property_id).all
      end



     #Display the property from Showlist table 
      def showwish
        @renter=current_renter
        @properties=Wishlist.where(renter_id: @renter.id)
      end


      #Removing a property from wishlist
      def remove
        @wish=Wishlist.find(params[:id])
        @wish.destroy
        redirect_to wishlistp_path,notice: "removed successfully"
      end


      #Removing a property from the Rentedlist and replace the flag to 0 and mail
      #to those who added to wishlit as this property
      def unrent
        @unrent=Rentedlist.find(params[:id])
        #flag updation for rented or not
        @property=Property.find(@unrent.property_id)
        @property.update(flag: 0)
        @check=Wishlist.where(property_id: @property.id).all
        @check.each do |obj|
          @renter=Renter.find(obj.renter_id)
          @agent=Agent.find(@property.agent_id)
           UserMailer.propertyavailabe(@renter,@agent,@property).deliver_now
        end
        @unrent.destroy
        redirect_to rentedlistp_path,notice: " The property has been unrented"
      end


      
      private
    def property_params
        params.require(:@properties).permit(:name,  :agent_id,:address, :city, :rent, :bedrooms,:description, images: [])

    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/edit.html.erb
<html>
<head>

<style >
	
body{
	margin:0;
	color:#6a6f8c;
	background:#808080;
	font:600 16px/18px 'Open Sans',sans-serif;
  background-color: ; 
}

.btnr{
border: none;
  background-color: ;
  padding: 14px 28px;
  border-radius: 25px;
  font-size: 16px;
  cursor: pointer;
  color: white;
  display: inline-block;
  margin-left:12%;
}
.center{
  font-size:18px;
}
  .btn:hover {
   box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  }
	</style>

<body>

<div class="login-wrap">

	<div class="login-form"> <div class="sign-in-htm">
	<br>
<h1 class="heading">Editing property</h1>
 <br>
<%= form_for :property, url: property_path(@property), method: :patch do |f| %>
  <% if @property.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@property.errors.count, "error") %> prohibited
      this property from being saved:</h2>
    <ul>
    <% @property.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="group">
<p>
    <%= f.label :name ,class:"label"%><br>
    <%= f.text_field :name, class:"input" %>
    </p>
    
  <p>
    <%= f.label :address ,class:"label"%><br>
    <%= f.text_field :address , class:"input"%>
  </p>
     
  <p>
    <%= f.label :city,class:"label"%><br>
    <%= f.text_field :city, class:"input"%>
  </p>
     <div><span class="label" >Rent($)</span> <span class="labels">BEDROOMS</span></div>

   <%= f.number_field :rent, class:"inputs"%> 
    <%= f.text_field :bedrooms, class:"inputs1"%>
  </p>

  <p>
    <%= f.label :description, class:"label"%><br>
    <%= f.text_area :description, class:"input" %>
  </p>
 <p>
  <p>
<%= f.label :Addimages,class:"label"%>
 <%= f.file_field :images, multiple: true ,class:"input"%>
 </p>
 <%= link_to "Delete images",delimage_path(@property),class:"label"%>
 
 </p> 
 
  <br>
    <%= f.submit  "Save Changes" ,class:"btn"%>
  

<% end %>
 
 

app/views/properties/new.html.erb
<html>
<head>

<style >
body{
	margin:0;
	color:#6a6f8c;
	background:#808080;
	font:600 16px/18px 'Open Sans',sans-serif;
  background-color: ; 
}

.btnr{
border: none;
  background-color: ;
  padding: 14px 28px;
  border-radius: 25px;
  font-size: 16px;
  cursor: pointer;
  color: white;
  display: inline-block;
  margin-left:12%;
}


.btn {
  border: none;
  background-color: blue;
  padding: 14px 28px;
  border-radius: 12px;
  font-size: 16px;
  cursor: pointer;
  color: black;
  display: inline-block;
}
.btn:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
}

	</style>

</head>
<body>
<div class="login-wrap">

	<div class="login-form">
	<div class="sign-in-htm">
 <h1 class="heading"> Properties Page</h1>

 
<%= form_for :@properties, url:'/properties'   do |f| %>
<div class="group">
<p>
    <%= f.label :name ,class:"label"%><br>
    <%= f.text_field :name, class:"input" %>
    </p>
    
  <p>
    <%= f.label :address ,class:"label"%><br>
    <%= f.text_field :address , class:"input"%>
  </p>
     
  <p>
    <%= f.label :city,class:"label"%><br>
    <%= f.text_field :city, class:"input"%>
  </p>
     
  <p>
  <div><span class="label" >Rent($)</span> <span class="labels">BEDROOMS</span></div>

   <%= f.number_field :rent, class:"inputs"%> 
    <%= f.text_field :bedrooms, class:"inputs1"%>
  </p>
  <p>
    <%= f.label :description, class:"label"%><br>
    <%= f.text_area :description, class:"input" %>
  </p>

  <p>
<%= f.label :Addimages,class:"label"%>
 <%= f.file_field :images, multiple: true ,class:"input"%>
 </p>
  <br>
    <%= f.submit  "Add properties" ,class:"btnr"%>
  <% if flash[:messages] %>
    <% flash[:messages].each do |message| %>
      <h2><%= message%></h2> <br>
    <% end %>
  <% end %>

<% end %>
 
 

app/views/properties/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.sidebtn{
  margin-left:90%;
  border: none;
  background-color:#333333;
  border-radius: 5px;
  font-size: 13px;
  padding: 4px 4px;
  color:white;
  cursor: pointer;
  display: inline-block;

}
.rating{
  margin-left:25px;
  border-radius:30px;
  width:10%;
  padding:10px;
}
.review{
  margin-left:25px;
  border-radius:15px;
  width:35%;
  padding:5px;
}
.alignment{
  margin-left:5%;
  color:#8c8c8c

}
.sidebtn:hover{
	  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
	}
  .leftpad{
    margin-left:30%;
    width:50%;
  }
</style>

</head>
<body>
 <ul>
  <li><%=link_to "back",viewprop_path, class:"active"%></li>
  <li style="float:right"><%= link_to "logout", destroy_renter_session_path, method: :delete %></li>
  </ul>
<br><br>
<div class="center">
Welcome <%=@renter.name%>
<br>

</div>
<br>
<%# if the particular property is not rentd means then we can approach that property%>
<%@rentercheckflag=0%>
<% if @property.flag == 0%>
<%if @approachflag == 1%>
<div class="alignment" >your Approaches has been updated</div>
<%else%>
<div class="sidebtn">
<%= link_to "Approach Property", addapproach_path(@property)%></div>
<%end%>
<%else%>
<%if @check.renter_id == current_renter.id %>
<div class="alignment" >The Agent Approved your request, check your mail and get connect with the agent:</div>
<%@rentercheckflag=1%>
<%else%>
<div class="alignment">Sorry, This Property has been already booked by another renter, 
Still you can add it to your wishlist</div>

<%= link_to "Add to wishlist", addwishlist_path(@property),class:"sidebtn"%>

<%end%>
<%end%>
<br>
<br>
<table class="leftpad">
  <tr>
    <th>Property Name:</th>
    <td><%= @property.name%></td>
  </tr>
  <tr>
    <th>Property rent:</th>
    <td><%= @property.rent%></td>
  </tr>
  <tr>
    <th>Property Location:</th>
    <td><%= @property.address%></td>
  </tr>
  <tr>
    <th>Property City</th>
    <td><%= @property.city%></td>
  </tr>
  <tr>
    <th>Number of bedrooms</th>
    <td><%= @property.bedrooms%></td>
  </tr>
  <tr>
    <th>About Property:</th>
    <td><%= @property.description%></td>
  </tr>
</table>
<br>
<div class="center">Property Images:
<br><br>

<%(0...@property.images.count).each do |img| %>

   <a href=""> <%= image_tag(@property.thumbnail(img)) %></a>
 

<%end%>
</div>
<br>
<%if @rentercheckflag==1%>
<div class="alignment">provide some ratings and reviews </div>
<%= form_for :@reviews, url:'/reviews'   do |f| %>
<div class="group">
<p>
    <%= f.label :rating,class:"rating"%><br>
    <%= f.number_field :rating,class:"rating",placeholder: "    Out of five",max: 5%>
    </p>
    
    <%= f.label :reviews, class:"rating"%><br>
    <%= f.text_area :reviews,class:"review" %>
  </p>
<%= f.hidden_field :property_id, value: @property.id %>
  
    <%= f.submit  "Add Reviews" ,class:"btn"%>
</div>
<%end%>
<%end%><br>
<% @reviewslist.each do|review|%>
<div>
<% @rentername=Renter.find(review.renter_id)%>
<div class="alignment">Name:
<%=@renter.name%></div>
<br>
<div class="alignment">Reviews:
<%=review.reviews%></div>
<br>
<div class="alignment">Ratings:
<%= review.rating %></div>
<hr>
</div>
<%end%>
</body>

app/views/properties/showrented.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
  .btns{
    margin-left:5%;
    background-color:#333333;
  }
  .btn2{
  border: none;
  margin-left:40%;
  background-color:#333333;
  border-radius: 5px;
  font-size: 13px;
  padding: 4px 4px;
  color:white;
  cursor: pointer;
  display: inline-block;}
  .center{
    color:
  }
  </style>
  <ul>
  <li><%=link_to "back",viewprop_path, class:"active"%></li>
  <li style="float:right"><%= link_to "logout", destroy_renter_session_path, method: :delete %></li>
  </ul>

	<div class="login-form">
	<div class="sign-in-htm">
<br>
<h1 class="center"> Welcome <%=@renter.name%></h1>

<h3 class="center"><i>Your rented lists</i></h3>

<% @properties.each do |prop|%>

<div class="clearfix">
<div class="box">


<% prop = Property.find(prop.property_id)%>
	
<%=link_to "unrent", unrent_path(prop), class:"btns"%>
	<%= link_to "View property", viewproperty_path(prop),class:"btn2"%>
	
		<h2 class="propname"><%= prop.name%><br></h2>
		

	<%(0...prop.images.count+1 - prop.images.count).each do |img| %>
   <a href=""> <%= image_tag(prop.thumbnail(img),class:"br") %></a>
   <%end%>
   		<br><br>
   		<span class="textd">Property Location :</span>
		<span class="border"><%= prop.address %></span><br>
		<div><span class="textd" >Rent($)</span> &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&ensp;<span class="textd">Bedrooms</span></div>
		<div class="rent"><%= prop.rent%></div>

		<div class="bedrooms"><%= prop.bedrooms%></div><br><br>
		<span class="textd">City</span>
		<div class="border"><%=prop.city%></div>
		
		<span class="textd" >About Property</span>

		<span class="border"><%= prop.description%></span>
		
		
			</div>
		<div>
		<% end %>

app/views/properties/showwish.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<style >
	.btns{
    margin-left:5%;
    background-color:#333333;
  }
  .btn2{
  border: none;
  margin-left:40%;
  background-color:#333333;
  border-radius: 5px;
  font-size: 13px;
  padding: 4px 4px;
  color:white;
  cursor: pointer;
  display: inline-block;}
</style>

  <ul>
  <li><%=link_to "back",viewprop_path, class:"active"%></li>
  <li style="float:right"><%= link_to "logout", destroy_renter_session_path, method: :delete %></li>
  </ul>



<h1 class="center"> Welcome <%=@renter.name%></h1>

	<div class="login-form">
	<div class="sign-in-htm">

<h3 class="center"><i>Your wish lists</i></h3>
<% if @properties == nil %>
<% puts "noproperties"%>
<%end%>
<% @properties.each do |prop|%>

<div class="clearfix">
<div class="box" style="background-color: ">

<% prop = Property.find(prop.property_id)%>
<div class="btns"><%=link_to "Remove", remove_path(prop)%></div>
<%= link_to "View property", viewproperty_path(prop),class:"btn2"%>
	
	
		<h2 class="propname"><%= prop.name%><br></h2>
		

	<%(0...prop.images.count+1 - prop.images.count).each do |img| %>
   <a href=""> <%= image_tag(prop.thumbnail(img),class:"br") %></a>
   <%end%>
   		<br><br>
   		<span class="textd">Property Location :</span>
		<span class="border"><%= prop.address %></span><br>
		<div><span class="textd" >Rent($)</span> &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&ensp;<span class="textd">Bedrooms</span></div>
		<div class="rent"><%= prop.rent%></div>

		<div class="bedrooms"><%= prop.bedrooms%></div><br><br>
		<span class="textd">City</span>
		<div class="border"><%=prop.city%></div>
		
		<span class="textd" >About Property</span>

		<span class="border"><%= prop.description%></span>
			</div>
		<div>
		<% end %>