config/routes.rb
Rails.application.routes.draw do
  devise_for :renters
  devise_for :agents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'main#index'
get '/delimage/:id'=>"agent#delimage", as: :delimage
get '/unrent/:id' => 'properties#unrent' , as: :unrent
get '/remove/:id' => 'properties#remove' , as: :remove
get '/addprop/:id' => 'properties#new', as: :addprop
get '/viewproperty/:id' => 'properties#show', as: :viewproperty
get '/displayprop', action: :show, controller: 'agent'
get '/viewprop', action: :show, controller: 'renter'
get '/addapproach/:id', action: :addapproach, controller: 'agent', as: :addapproach
get '/addrentedprop/:id', action: :addrented, controller: 'properties', as: :addrentedprop
get '/addwishlist/:id', action: :addwish, controller: 'properties', as: :addwishlist
get '/rentedlistpath', action: :showrented, controller: 'properties', as: :rentedlistp
get '/wishlistpath', action: :showwish, controller: 'properties', as: :wishlistp
post '/reviews', action: :create, controller: 'review', as: :reviews
get '/delimageattachment/:id', action: :delete_image_attachment, controller: :agent, method: :delete,as: :delimageattachment 
get '/viewapproachedlist/:id', action: :viewapproach, controller: 'agent',as: :viewapproach
post '/create', action: :create, controller: :company
resources :properties
resources :company
end

app/models/renter.rb
class Renter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
         :token_authenticatable
    has_many :rentedlists,dependent: :destroy
    has_many :wishlists,dependent: :destroy
    has_many :approaches, dependent: :destroy

validates :password, 
                format: { with: /\A(?=.*\d)(?=.*[A-Z])(?=.*\W)[^ ]{7,}\z/,
                          message: 'should have more than 7 characters including 1 uppercase letter, 1 number, 1 special character'
                        }
    
    
end

app/controllers/renter_controller.rb
class RenterController < ApplicationController
    def show
        @propertylist=Property.all
        @renter=current_renter
    end
end

app/helpers/renter_helper.rb
module RenterHelper
end

app/views/renter/show.html.erb
<!DOCTYPE html>
<html>
<head>


<ul>
  <li><%= link_to "RentedList", rentedlistp_path ,class:"active"%></li>
  <li><%= link_to "Wishlist",wishlistp_path, style: 'color: #FFFFFF' %></li>
   <li style="float:right"><%= link_to "logout", destroy_renter_session_path, method: :delete %></li>
</ul>

<h1 class="center"> Welcome <%=@renter.name%></h1>


	<div class="login-form"> <div class="sign-in-htm">
	
	<% @propertylist.each do |prop|%>
		<div class="clearfix">
		<div class="box">
		<button class="btn1">
	<%= link_to "View property", viewproperty_path(prop)%>
	</button>
		<h2 class="propname"><%= prop.name%><br></h2>
		

	<%(0...prop.images.count+1 - prop.images.count).each do |img| %>
   <a href=""> <%= image_tag(prop.thumbnail(img),class:"br") %></a>
   <%end%>
   		<br><br>
   		<span class="textd">Property Location :</span>
		<span class="border"><%= prop.address %></span><br>
		<div><span class="textd" >Rent($)</span> &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&ensp;<span class="textd">Bedrooms</span></div>
		<div class="rent"><%= prop.rent%></div>

		<div class="bedrooms"><%= prop.bedrooms%></div><br><br>
		<span class="textd">City</span>
		<div class="border"><%=prop.city%></div>
		
		<span class="textd" >About Property</span>

		<span class="border"><%= prop.description%></span>
			</div>
		<div>
		<% end %>

















			